### PR TITLE
Add Sinhala Language

### PR DESCRIPTION
**Pull request by MasterBrian99**
i modified other README files and add (- [සිංහල](./README-si.md)) this line. Nothing changes while translating.same as the original README file.

### CODE REVIEW

**Comment by tbetous** [comment]
Hi @MasterBrian99 !

I'll need to find someone who speeks Sinhala in order to review your PR. Don't worry if I don't merge it right now, i'm on it !

Thanks for opening this pull request ! 👍🇱🇰

**Comment by tbetous** [comment]
Hi @MasterBrian99 ! 👋 

Sorry for this late answer. I have struggled to find someone who was able to speak sinhala. A co-worker of mind was able to make this PR review. Here is his review :

- line 11: change "පරිශීලක" to "කේත ව්‍යාපෘති"
- line 30: change "දායකයත්වය සපයන්නන් පිළිගන්නවා." to "දායකත්වය සාදරයෙන් පිළිගනිමු."
- line 96: change "වි්‍යුහගත" to "ව්‍යුහගත"
- line 197: add "changelogs සාදන්න."
- line 224 : change "සතුට" to "තිලිණ"

He also said that "The commiter has done a good job !" so I would really say to you thank you to have made this translation possible.

Can you make the little changes suggested in the review ?

**Comment by MasterBrian99** [comment]
Thank you for giving me this chance.i fixed errors..

**Comment by tbetous** [comment]
@all-contributors please add @MasterBrian99  for translation

**Comment by tbetous** [comment]
It's good to me ! Good job ! Many thanks @MasterBrian99.

**Pull request merged**
