### PR TITLE
:globe_with_meridians: Add Turkish language

### PR DESCRIPTION
**Pull request by umutphp**
This document deserves to be translated to Turkish :)

### CODE REVIEW

**Comment by umutphp** [comment]
> Awesome! Could you add the turkish link the list of available languages and translate the "Share on twitter" badge?

Done :)

**Comment by kefranabg** [comment]
Could you add the turkish link in the other languages?

**Comment by umutphp** [comment]
> Could you add the turkish link in the other languages?

Done :)

**Comment by kefranabg** [comment]
@all-contributors please add umutphp for translation

**Pull request merged**
